# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ObjectLocker
                                 A QGIS plugin
 Sets the "Locked"attribute of objects to True
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-11-16
        copyright            : (C) 2021 by AtticDevelopment
        email                : bertcommeine@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ObjectLocker class from file ObjectLocker.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .object_locker import ObjectLocker
    return ObjectLocker(iface)
